server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: springboot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: springboot1
          __path__: /app1/logs/spring.log
      - targets:
          - localhost
        labels:
          job: springboot2
          __path__: /app2/logs/spring.log
      - targets:
          - localhost
        labels:
          job: caddy
          __path__: /caddy/logs/*.log